
/*
====================================================
DATABASE EXPLORATION
====================================================
*/

-- Explore All Objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES;

-- Explore All Columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS;

-- Explore All Countries from Customers Table
SELECT DISTINCT 
	country 
FROM gold.dim_customers;

-- Explore All Categories from Products Table
SELECT DISTINCT category FROM gold.dim_products;

-- Explore All Sub-Categories from Products Table
SELECT DISTINCT category, subcategory FROM gold.dim_products;

-- Explore All Products from Products Table
SELECT DISTINCT category, subcategory, product_name FROM gold.dim_products;

-- Find the First and Last Order Date from Sales Table
-- How many years and months of sales are available?
SELECT 
	MIN(order_date) AS first_order_date,
	MAX(order_date) AS last_order_date,
	DATEDIFF(year, MIN(order_date), MAX(order_date)) AS order_year_range,
	DATEDIFF(month, MIN(order_date), MAX(order_date)) AS order_month_range
FROM gold.fact_sales;

-- Find the Youngest and Oldest Customer
SELECT 
	MIN(birthdate) AS oldest_customer_birthdate,
	DATEDIFF(year, MIN(birthdate), GETDATE()) AS oldest_customer_age,
	MAX(birthdate) AS youngest_customer_birthdate,
	DATEDIFF(year, MAX(birthdate), GETDATE()) AS youngest_customer_age
FROM gold.dim_customers;

-- Explore Marital Status from Customers Table
SELECT DISTINCT marital_status FROM gold.dim_customers;

-- Explore Gender from Customers Table
SELECT DISTINCT gender FROM gold.dim_customers;

-- Total Sales
SELECT SUM(sales_amount) AS total_sales FROM gold.fact_sales;

-- Total Items Sold
SELECT SUM(quantity) AS total_items_sold FROM gold.fact_sales;

-- Average Order Value
SELECT AVG(price) AS average_order_value FROM gold.fact_sales;

-- Total Number of Orders
SELECT COUNT(DISTINCT order_number) AS total_number_orders FROM gold.fact_sales;

-- Total Number of Products
SELECT COUNT(DISTINCT product_key) AS total_number_products FROM gold.dim_products;

-- Total Number of Customers
SELECT COUNT(customer_key) AS total_customers FROM gold.dim_customers;

-- Total Number of Customers that Ordered
SELECT COUNT(DISTINCT customer_key) AS total_customers_that_ordered FROM gold.fact_sales;


/*
====================================================
MEASURES EXPLORATION
====================================================
*/

SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Items Sold', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Order Value', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total Number of Orders', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Number of Products', COUNT(DISTINCT product_key) FROM gold.dim_products
UNION ALL
SELECT 'Total Number of Customers', COUNT(DISTINCT customer_key) FROM gold.dim_customers


/*
====================================================
MAGNITUDE ANALYSIS
====================================================
*/

-- Total Number of Customers per Country
SELECT 
	country, 
	COUNT(customer_key) AS customers,
	ROUND(100.0 * COUNT(customer_key) / SUM(COUNT(customer_key)) OVER(), 2) AS percentage_distribution
FROM gold.dim_customers 
GROUP BY country 
ORDER BY customers DESC;

-- Total Number of Customers Based on Marital Status
SELECT 
	marital_status, 
	COUNT(customer_key) AS customers,
	ROUND(100.0 * COUNT(customer_key) / SUM(COUNT(customer_key)) OVER(), 2) AS percentage_distribution
FROM gold.dim_customers 
GROUP BY marital_status 
ORDER BY customers DESC;

-- Total Number of Customers Based on Gender
SELECT 
	gender, 
	COUNT(customer_key) AS customers, 
	ROUND(100.0 * COUNT(customer_key) / SUM(COUNT(customer_key)) OVER(), 2) AS percentage_distribution
FROM gold.dim_customers 
GROUP BY gender 
ORDER BY customers DESC;

-- Total Number of Products per Category
SELECT 
	category, 
	COUNT(product_key) AS products,
	ROUND(100.0 * COUNT(product_key) / SUM(COUNT(product_key)) OVER(), 2) AS percentage_distribution
FROM gold.dim_products
GROUP BY category
ORDER BY products DESC;

-- Average Cost of Each Category
SELECT 
	category, 
	AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;

-- Total Revenue Generated of Each Category
SELECT
	p.category, 
	SUM(s.sales_amount) AS revenue_generated,
	ROUND(100.0 * SUM(s.sales_amount) / SUM(SUM(s.sales_amount)) OVER(), 2) AS percentage_distribution
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_products AS p ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY revenue_generated DESC;

-- Total Revenue Generated by Each Customer
SELECT
	c.customer_key,
	CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
	SUM(s.sales_amount) AS revenue_generated
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c ON c.customer_key = s.customer_key
GROUP BY 
	c.customer_key, 
	CONCAT(c.first_name, ' ', c.last_name)
ORDER BY revenue_generated DESC;

-- Distribution of Items Sold Across Countries
SELECT
	c.country,
	SUM(s.quantity) AS total_sold_items,
	ROUND(100.0 * SUM(s.quantity) / SUM(SUM(s.quantity)) OVER(), 2) AS percentage_distribution
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;


/*
====================================================
RANKING ANALYSIS
====================================================
*/

-- Top 5 Product by Revenue
SELECT TOP 5
	p.product_name, 
	SUM(s.sales_amount) AS revenue_generated
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_products AS p ON p.product_key = s.product_key
GROUP BY p.product_name
ORDER BY revenue_generated DESC;

-- Worst 5 Product by Revenue
SELECT TOP 5
	p.product_name, 
	SUM(s.sales_amount) AS revenue_generated
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_products AS p ON p.product_key = s.product_key
GROUP BY p.product_name
ORDER BY revenue_generated;

-- Top 5 Sub-Category by Revenue
SELECT TOP 5
	p.subcategory, 
	SUM(s.sales_amount) AS revenue_generated
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_products AS p ON p.product_key = s.product_key
GROUP BY p.subcategory
ORDER BY revenue_generated DESC;

-- Worst 5 Sub-Category by Revenue
SELECT TOP 5
	p.subcategory, 
	SUM(s.sales_amount) AS revenue_generated
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_products AS p ON p.product_key = s.product_key
GROUP BY p.subcategory
ORDER BY revenue_generated;

-- Top 10 Customers with Highest Revenue Generated
SELECT TOP 10
	c.customer_key,
	CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
	SUM(s.sales_amount) AS revenue_generated
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c ON c.customer_key = s.customer_key
GROUP BY 
	c.customer_key, 
	CONCAT(c.first_name, ' ', c.last_name)
ORDER BY revenue_generated DESC;

-- Top 10 Customers with Most Orders
SELECT TOP 10
	c.customer_key,
	CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
	COUNT(s.order_number) AS orders_placed
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c ON c.customer_key = s.customer_key
GROUP BY 
	c.customer_key, 
	CONCAT(c.first_name, ' ', c.last_name)
ORDER BY orders_placed DESC;


/*
====================================================
CHANGE OVER TIME ANALYSIS
====================================================
*/

-- Analyze Sales Performance, Customers and Items Sold Over the Years
SELECT
	YEAR(order_date) as year,
	SUM(sales_amount) as total_sales,
	COUNT(DISTINCT customer_key) as total_customers,
	COUNT(product_key) as total_customers
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY YEAR(order_date)
ORDER BY YEAR(order_date);

-- Analyze Sales Performance, Customers and Items Sold Over Time
SELECT
	DATETRUNC(month, order_date) as date,
	SUM(sales_amount) as total_sales,
	COUNT(DISTINCT customer_key) as total_customers,
	COUNT(product_key) as total_customers
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(month, order_date)
ORDER BY DATETRUNC(month, order_date);


/*
====================================================
CHANGE OVER TIME ANALYSIS
====================================================
*/

-- Sales Performance Over Time
SELECT
    DATETRUNC(month, order_date) AS order_date,
    SUM(sales_amount) AS total_sales,
    COUNT(DISTINCT customer_key) AS total_customers,
    SUM(quantity) AS total_quantity
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(month, order_date)
ORDER BY DATETRUNC(month, order_date);

SELECT
	order_date,
	total_sales,
	SUM(total_sales) OVER (ORDER BY order_date) AS running_total_sales,
	AVG(avg_price) OVER (ORDER BY order_date) AS running_avg_price
	FROM (
		SELECT
			DATETRUNC(month, order_date) as order_date,
			SUM(sales_amount) AS total_sales,
			AVG(price) AS avg_price
		FROM gold.fact_sales
		WHERE order_date IS NOT NULL
		GROUP BY DATETRUNC(month, order_date)
	) as sales_over_time;


/*
====================================================
PERFORMANCE ANALYSIS
====================================================
*/

-- Performance of Products Compared to their Average Sales Performance and Previous Year's Sales
WITH yearly_product_sales AS (
	SELECT
		YEAR(order_date) AS order_year,
		p.product_name,
		SUM(s.sales_amount) AS current_sales
	FROM gold.fact_sales AS s
	LEFT JOIN gold.dim_products AS p ON p.product_key = s.product_key
	WHERE order_date IS NOT NULL
	GROUP BY 
		YEAR(order_date),
		p.product_name
)
SELECT 
	order_year,
	product_name,
	current_sales,
	AVG(current_sales) OVER (PARTITION BY product_name) AS avg_sales,
	current_sales - AVG(current_sales) OVER (PARTITION BY product_name) AS diff_avg,
	CASE
		WHEN current_sales - AVG(current_sales) OVER (PARTITION BY product_name) > 0 THEN 'Above Average'
		WHEN current_sales - AVG(current_sales) OVER (PARTITION BY product_name) < 0 THEN 'Below Average'
		ELSE 'Average'
	END avg_change,

	-- Year over Year Analysis
	LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year) AS py_sales,
	current_sales - LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year) AS diff_py,
	CASE
		WHEN current_sales - LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year) > 0 THEN 'Increase'
		WHEN current_sales - LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year) < 0 THEN 'Decrease'
		ELSE 'No Change'
	END avg_change
FROM yearly_product_sales
ORDER BY product_name, order_year;


/*
====================================================
PART-TO-WHOLE ANALYSIS / PROPORTIONAL ANALYSIS
====================================================
*/

-- Contribution of Categories to Overeall Sales
WITH category_sales AS (
	SELECT
		p.category,
		SUM(s.sales_amount) AS total_sales
	FROM gold.fact_sales AS s
	LEFT JOIN gold.dim_products AS p ON p.product_key = s.product_key
	GROUP BY p.category
)
SELECT
	category,
	total_sales,
	SUM(total_sales) OVER () AS overall_sales,
	CONCAT(ROUND((CAST(total_sales AS FLOAT) / SUM(total_sales) OVER ()) * 100, 2), '%') AS pctg_of_total
FROM category_sales
ORDER BY total_sales DESC;


/*
====================================================
DATA SEGMENTATION
====================================================
*/

-- Product-Cost Segmentation
WITH product_segments AS (
	SELECT
		product_key,
		product_name,
		cost,
		CASE
			WHEN cost < 100 THEN 'Below 100'
			WHEN cost BETWEEN 100 AND 500 THEN '100 - 500'
			WHEN cost BETWEEN 500 AND 1000 THEN '500 - 1000'
			ELSE 'Above 1000'
		END AS cost_range
	FROM gold.dim_products
)
SELECT
	cost_range,
	COUNT(product_key) AS total_products
FROM product_segments
GROUP BY cost_range
ORDER BY total_products DESC;

/* Customer Segmentation
	VIP: Customers with at least 12 months of history and spending more than 5,000.
	Regular: Customers with at least 12 months of history but spending 5,000 or less.
	New: Customers with a lifespan less than 12 months.
*/
WITH segmentation AS (
	SELECT
		c.customer_key AS customer,
		SUM(sales_amount) AS total_spent,
		MIN(order_date) AS first_order,
		MAX(order_date) AS last_order,
		DATEDIFF (month, MIN(order_date), MAX(order_date)) AS lifespan
	FROM gold.fact_sales AS s
	LEFT JOIN gold.dim_customers AS c ON c.customer_key = s.customer_key 
	GROUP BY c.customer_key
)
SELECT
	customer_segment,
	COUNT(customer) AS total_customers
FROM (
	SELECT
		customer,
		total_spent,
		lifespan,
		CASE
			WHEN lifespan >= 12 AND total_spent > 5000 THEN 'VIP'
			WHEN lifespan >= 12 AND total_spent <= 5000 THEN 'Regular'
			ELSE 'New'
		END AS customer_segment
	FROM segmentation
) AS customer_segmentation
GROUP BY customer_segment
ORDER BY total_customers DESC;

GO


/*
====================================================
REPORTING
====================================================
*/

/* Customer Report
	Purpose: Consolidate key customer metrics and behaviors.
	Highlights:
		1. Gather essential fields such as names, ages, and transaction details.
		2. Segments customers into categories (VIP, Regular, New) and age groups.
		3. Aggregates customer-level metrics:
		   - Total Orders
		   - Total Spent
		   - Total Items Ordered
		   - Total Products Ordered
		   - Lifespan (Months)
		4. Calculates valuable KPIs:
			- Recency (months since last order)
			- Average Order Value
			- Average Monthly Spend
*/

CREATE VIEW gold.report_customers AS
/*
----------------------------------------------------
1) Base Query: Retrieves core columns from tables
----------------------------------------------------
*/
WITH base_query AS (
	SELECT
		s.order_number,
		s.product_key,
		s.order_date,
		s.sales_amount,
		s.quantity,
		c.customer_key,
		c.customer_number,
		CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
		DATEDIFF(YEAR, c.birthdate, GETDATE()) AS age
	FROM gold.fact_sales AS s
	LEFT JOIN gold.dim_customers AS c ON c.customer_key = s.customer_key
	WHERE order_date IS NOT NULL

), customer_aggregation AS (
/*
------------------------------------------------------------------------
2) Customer Aggregations: Summarizes key metrics at the customer level
------------------------------------------------------------------------
*/
	SELECT
		customer_key,
		customer_number,
		customer_name,
		age,
		SUM(sales_amount) AS total_spent,
		COUNT(DISTINCT order_number) as total_orders,
		SUM(quantity) AS total_items_ordered,
		COUNT(DISTINCT product_key) AS total_products_ordered,
		MAX(order_date) AS last_order_date,
		DATEDIFF (month, MIN(order_date), MAX(order_date)) AS lifespan
	FROM base_query
	GROUP BY 
		customer_key,
		customer_number,
		customer_name,
		age
)
SELECT 
	customer_key,
	customer_number,
	customer_name,
	age,
	CASE
		WHEN age < 18 THEN 'Under 18'
		WHEN age BETWEEN 18 AND 24 THEN '18-24'
		WHEN age BETWEEN 25 AND 34 THEN '25-34'
		WHEN age BETWEEN 35 AND 44 THEN '35-44'
		WHEN age BETWEEN 45 AND 54 THEN '45-54'
		WHEN age BETWEEN 55 AND 64 THEN '55-64'
		ELSE '65 and Over'
	END AS age_group,
	CASE
		WHEN lifespan >= 12 AND total_spent > 5000 THEN 'VIP'
		WHEN lifespan >= 12 AND total_spent <= 5000 THEN 'Regular'
		ELSE 'New'
	END AS customer_segment,
	last_order_date,
	DATEDIFF(MONTH, last_order_date, GETDATE()) AS recency,
	total_spent,

	-- Average Order Value
	CASE
		WHEN total_spent = 0 THEN 0
		ELSE total_spent / total_orders
	END AS avg_order_value,

	-- Average Monthly Spend
	CASE
		WHEN lifespan = 0 THEN total_spent
		ELSE total_spent / lifespan
	END AS avg_monthly_spent,

	total_orders,
	total_items_ordered,
	total_products_ordered,
	lifespan
FROM customer_aggregation;

GO

/* Product Report
	Purpose: Consolidate key product metrics and behaviors.
	Highlights:
		1. Gather essential fields such as names, ages, and transaction details.
		2. Segments products by revenue to identify High-Performers, Mid-Range, or Low-Performers.
		3. Aggregates product-level metrics:
		   - Total Orders
		   - Total Sales
		   - Total Items Ordered
		   - Total Customers (Unique)
		   - Lifespan (Months)
		4. Calculates valuable KPIs:
			- Recency (months since last sale)
			- Average Order Revenue
			- Average Monthly Revenue
*/

CREATE VIEW gold.report_products AS
/*
------------------------------------------------------------------------
1) Base Query: Retrieves core columns from fact_sales and dim_products
------------------------------------------------------------------------
*/
WITH base_query AS (
	SELECT
		s.order_number,
		s.customer_key,
		s.order_date,
		s.sales_amount,
		s.quantity,
		p.product_key,
		p.product_name,
		p.category,
		p.subcategory,
		p.cost
	FROM gold.fact_sales AS s
	LEFT JOIN gold.dim_products AS p ON p.product_key = s.product_key
	WHERE order_date IS NOT NULL

), product_aggregation AS (
/*
------------------------------------------------------------------------
2) Product Aggregations: Summarizes key metrics at the product level
------------------------------------------------------------------------
*/
	SELECT
		product_key,
		product_name,
		category,
		subcategory,
		cost,
		SUM(sales_amount) AS total_sales,
		COUNT(DISTINCT order_number) as total_orders,
		SUM(quantity) AS total_items_ordered,
		COUNT(DISTINCT customer_key) AS total_customers,
		MAX(order_date) AS last_sale_date,
		DATEDIFF (month, MIN(order_date), MAX(order_date)) AS lifespan
	FROM base_query
	GROUP BY
		product_key,
		product_name,
		category,
		subcategory,
		cost
	)
SELECT
	product_key,
	product_name,
	category,
	subcategory,
	cost,
	total_sales,

	-- Average Order Revenue (AOR)
	CASE 
		WHEN total_orders = 0 THEN 0
		ELSE total_sales / total_orders
	END AS avg_order_revenue,

	-- Average Monthly Revenue
	CASE
		WHEN lifespan = 0 THEN total_sales
		ELSE total_sales / lifespan
	END AS avg_monthly_revenue,

	total_orders,
	total_items_ordered,
	total_customers,
	last_sale_date,
	DATEDIFF(MONTH, last_sale_date, GETDATE()) AS recency,
	CASE
		WHEN total_sales > 50000 THEN 'High-Performer'
		WHEN total_sales >= 10000 THEN 'Mid-Range'
		ELSE 'Low-Performer'
	END AS product_segment,
	lifespan
FROM product_aggregation;